name: Backend Deploy

on:
  push:
   paths:
    - sb-backend/**
   branches:
    - main
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sb-app-api"
          heroku_email: "sailboatapp@gmail.com"
