name: PR Validator

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  workflow_dispatch:

jobs:
  
  pull_request_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: deepakputhraya/action-branch-name@master
        name: Branch name validation
        with:
          regex: 'SBIT-\d+-*'
          
      - uses: deepakputhraya/action-pr-title@master
        name: PR title validation
        with:
          regex: '\[SBIT-\d+\]: \w'
