name: sb-backend-pr-check

on:
  pull_request:
    types: ['opened', 'reopened']
    paths:
      - sb-backend/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Install dependencies
        working-directory: ./sb-backend
        run: dotnet restore
        
      - name: Build
        working-directory: ./sb-backend
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        working-directory: ./sb-backend
        run: dotnet test 
