name: sb-web PR check

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths:
      - sb-web/**
  workflow_dispatch:

jobs:
  pull_request_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dylanvann/check-pull-request-title@v1
        with:
          pattern: '[SBIT-\d*]:'

  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./sb-web
        run: yarn install
      - name: Lint code
        working-directory: ./sb-web
        run: yarn lint
      - name: Test code
        working-directory: ./sb-web
        run: yarn test
